//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DendoSoapSample.DendoService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="https://musewiki.dip.jp/dendoweb/DendoRank/DendoService1.asmx", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="https://musewiki.dip.jp/dendoweb/DendoRank/DendoService1.asmx", ConfigurationName="DendoService.DendoService1Soap")]
    public interface DendoService1Soap {
        
        // CODEGEN: 名前空間 https://musewiki.dip.jp/dendoweb/DendoRank/DendoService1.asmx の要素名 HelloWorldResult が nillable に設定されていないため、メッセージ コントラクトを生成しています
        [System.ServiceModel.OperationContractAttribute(Action="https://musewiki.dip.jp/dendoweb/DendoRank/DendoService1.asmx/HelloWorld", ReplyAction="*")]
        DendoSoapSample.DendoService.HelloWorldResponse HelloWorld(DendoSoapSample.DendoService.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://musewiki.dip.jp/dendoweb/DendoRank/DendoService1.asmx/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<DendoSoapSample.DendoService.HelloWorldResponse> HelloWorldAsync(DendoSoapSample.DendoService.HelloWorldRequest request);
        
        // CODEGEN: 名前空間 https://musewiki.dip.jp/dendoweb/DendoRank/DendoService1.asmx の要素名 DendoRankResult が nillable に設定されていないため、メッセージ コントラクトを生成しています
        [System.ServiceModel.OperationContractAttribute(Action="https://musewiki.dip.jp/dendoweb/DendoRank/DendoService1.asmx/DendoRank", ReplyAction="*")]
        DendoSoapSample.DendoService.DendoRankResponse DendoRank(DendoSoapSample.DendoService.DendoRankRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://musewiki.dip.jp/dendoweb/DendoRank/DendoService1.asmx/DendoRank", ReplyAction="*")]
        System.Threading.Tasks.Task<DendoSoapSample.DendoService.DendoRankResponse> DendoRankAsync(DendoSoapSample.DendoService.DendoRankRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="https://musewiki.dip.jp/dendoweb/DendoRank/DendoService1.asmx", Order=0)]
        public DendoSoapSample.DendoService.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(DendoSoapSample.DendoService.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="https://musewiki.dip.jp/dendoweb/DendoRank/DendoService1.asmx", Order=0)]
        public DendoSoapSample.DendoService.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(DendoSoapSample.DendoService.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://musewiki.dip.jp/dendoweb/DendoRank/DendoService1.asmx")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public DendoSoapSample.DendoService.ArrayOfString HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(DendoSoapSample.DendoService.ArrayOfString HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DendoRankRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DendoRank", Namespace="https://musewiki.dip.jp/dendoweb/DendoRank/DendoService1.asmx", Order=0)]
        public DendoSoapSample.DendoService.DendoRankRequestBody Body;
        
        public DendoRankRequest() {
        }
        
        public DendoRankRequest(DendoSoapSample.DendoService.DendoRankRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://musewiki.dip.jp/dendoweb/DendoRank/DendoService1.asmx")]
    public partial class DendoRankRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        public DendoRankRequestBody() {
        }
        
        public DendoRankRequestBody(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DendoRankResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DendoRankResponse", Namespace="https://musewiki.dip.jp/dendoweb/DendoRank/DendoService1.asmx", Order=0)]
        public DendoSoapSample.DendoService.DendoRankResponseBody Body;
        
        public DendoRankResponse() {
        }
        
        public DendoRankResponse(DendoSoapSample.DendoService.DendoRankResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://musewiki.dip.jp/dendoweb/DendoRank/DendoService1.asmx")]
    public partial class DendoRankResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public DendoSoapSample.DendoService.ArrayOfString[] DendoRankResult;
        
        public DendoRankResponseBody() {
        }
        
        public DendoRankResponseBody(DendoSoapSample.DendoService.ArrayOfString[] DendoRankResult) {
            this.DendoRankResult = DendoRankResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface DendoService1SoapChannel : DendoSoapSample.DendoService.DendoService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DendoService1SoapClient : System.ServiceModel.ClientBase<DendoSoapSample.DendoService.DendoService1Soap>, DendoSoapSample.DendoService.DendoService1Soap {
        
        public DendoService1SoapClient() {
        }
        
        public DendoService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DendoService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DendoService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DendoService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DendoSoapSample.DendoService.HelloWorldResponse DendoSoapSample.DendoService.DendoService1Soap.HelloWorld(DendoSoapSample.DendoService.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public DendoSoapSample.DendoService.ArrayOfString HelloWorld() {
            DendoSoapSample.DendoService.HelloWorldRequest inValue = new DendoSoapSample.DendoService.HelloWorldRequest();
            inValue.Body = new DendoSoapSample.DendoService.HelloWorldRequestBody();
            DendoSoapSample.DendoService.HelloWorldResponse retVal = ((DendoSoapSample.DendoService.DendoService1Soap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DendoSoapSample.DendoService.HelloWorldResponse> DendoSoapSample.DendoService.DendoService1Soap.HelloWorldAsync(DendoSoapSample.DendoService.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<DendoSoapSample.DendoService.HelloWorldResponse> HelloWorldAsync() {
            DendoSoapSample.DendoService.HelloWorldRequest inValue = new DendoSoapSample.DendoService.HelloWorldRequest();
            inValue.Body = new DendoSoapSample.DendoService.HelloWorldRequestBody();
            return ((DendoSoapSample.DendoService.DendoService1Soap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DendoSoapSample.DendoService.DendoRankResponse DendoSoapSample.DendoService.DendoService1Soap.DendoRank(DendoSoapSample.DendoService.DendoRankRequest request) {
            return base.Channel.DendoRank(request);
        }
        
        public DendoSoapSample.DendoService.ArrayOfString[] DendoRank(int id) {
            DendoSoapSample.DendoService.DendoRankRequest inValue = new DendoSoapSample.DendoService.DendoRankRequest();
            inValue.Body = new DendoSoapSample.DendoService.DendoRankRequestBody();
            inValue.Body.id = id;
            DendoSoapSample.DendoService.DendoRankResponse retVal = ((DendoSoapSample.DendoService.DendoService1Soap)(this)).DendoRank(inValue);
            return retVal.Body.DendoRankResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DendoSoapSample.DendoService.DendoRankResponse> DendoSoapSample.DendoService.DendoService1Soap.DendoRankAsync(DendoSoapSample.DendoService.DendoRankRequest request) {
            return base.Channel.DendoRankAsync(request);
        }
        
        public System.Threading.Tasks.Task<DendoSoapSample.DendoService.DendoRankResponse> DendoRankAsync(int id) {
            DendoSoapSample.DendoService.DendoRankRequest inValue = new DendoSoapSample.DendoService.DendoRankRequest();
            inValue.Body = new DendoSoapSample.DendoService.DendoRankRequestBody();
            inValue.Body.id = id;
            return ((DendoSoapSample.DendoService.DendoService1Soap)(this)).DendoRankAsync(inValue);
        }
    }
}
